apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "item-service.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "item-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "item-service.name" . }}
    spec:
      containers:
        - name: item-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.config.serverPort }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.config.datasourceUrl | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.config.datasourceUsername | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "item-service.fullname" . }}-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: {{ .Values.config.hibernateDdlAuto | quote }}
            - name: SERVER_PORT
              value: {{ .Values.config.serverPort | quote }}
